version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install bcmath

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
